encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("nosuchentry", views.nosuchentry, name="noSuchEntry"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("searching", views.searching, name="searching"),
    path("randomed", views.randomed, name="randomed"),
    path("create", views.create, name="create"),
    path("edit", views.edit, name="edit"),
    path("exists", views.exists, name="exists"),
    path("<str:entryname>", views.entryname, name="entryname")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
import random
from . import util
from django.core.files.base import ContentFile

markdowner = Markdown()

class NewTaskForm(forms.Form):
    title = forms.CharField(label="Title")
    body = forms.CharField(widget=forms.Textarea(), label="Bodycopy")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def nosuchentry(request):
    return render(request, "encyclopedia/nosuchentry.html")

def exists(request):
    return render(request, "encyclopedia/exists.html")

def searching(request):
    if request.method == "POST":
        title = request.POST.__getitem__("title")
        entrieslist = util.list_entries()

        for entry in entrieslist:
            if title.lower() == entry.lower():
                return HttpResponseRedirect(f"/wiki/{entry}")
        
        resultlist = []
        for entry in entrieslist:
            if title.lower() in entry.lower():
                resultlist.append(entry)
        
        if len(resultlist) == 0:
            return render(request, "encyclopedia/nosuchentry.html")
        else:
            return render(request, "encyclopedia/index.html", {
            "entries": resultlist
            })



def entry(request, title):
    entries = util.list_entries()
    for entry in entries:
        if title.lower() == entry.lower():
            return render(request, f"encyclopedia/entry.html", {
                "entryname": entry,
                "content": markdowner.convert(util.get_entry(title))
            })
    return HttpResponseRedirect("/nosuchentry")

def randomed(request):
    myrandom = random.choice(util.list_entries())
    return  HttpResponseRedirect(f"wiki/{myrandom}")

def create(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            body = form.cleaned_data["body"]
        
        if util.search(util.list_entries(), title):
            return HttpResponseRedirect(reverse("encyclopedia:exists"))

        else:
            with open(f'entries\\{title}.md', 'w+') as NewEntry:
                NewEntry.write(body)
            return HttpResponseRedirect("wiki/{title}".format(title=title))
        
    else:
        return render(request, "encyclopedia/create.html", {
            "form": NewTaskForm()
        })

def entryname(request, entryname):

        with open(f'entries\\{entryname}.md', 'r') as ExistingEntry:
            existing = ExistingEntry.read                

            class NewEntryForm(forms.Form):
                title = forms.CharField(label="Title", initial=entryname) 
                body = forms.CharField(label="Bodycopy", initial=existing, widget=forms.Textarea() )
            
            return render(request, "encyclopedia/edit.html", {
                "form": NewEntryForm()
            })
        
def edit(request):
        if request.method == "POST":
            form = NewTaskForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data["title"]
                body = form.cleaned_data["body"]
            with open(f'entries\\{title}.md', 'w+') as NewEntry:
                NewEntry.write(body)
            return HttpResponseRedirect("wiki/{title}".format(title=title))
        else:
            return render(request, "encyclopedia/edit.html", {
                "form": NewTaskForm()
            })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New entry
{% endblock %}

{% block body %}
<p>Use <a href="https://www.markdownguide.org/" target="new">markdown</a> to complete the fields!</p>
    <form action="{%url 'encyclopedia:create'%}" method="post" autocomplete="off">
        {% csrf_token %}
        {{form.as_p }}
        <input type="submit"  value="Create entry">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit entry
{% endblock %}

{% block body %}
<p>Use <a href="https://www.markdownguide.org/" target="new">markdown</a> to complete the fields!</p>
    <form action="{%url 'encyclopedia:edit'%}" method="post" autocomplete="off">
        {% csrf_token %}
        {{form.as_p }}
        <input type="submit" value="Save edits">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entryname }}
{% endblock %}

{% block body %}
    <div>
        <p>
            {{ content | safe}}
        </p>
        <p><a href="../{{ entryname }}">Edit entry</a></p>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/exists.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry already exists
{% endblock %}

{% block body %}
<h1>Entry already exists</h1>
<form>
 <input type="button" value="Go back!" onclick="history.back()">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:searching' %}" method="post" autocomplete="off">
                    {% csrf_token %}
                    <input class="search" type="text" name="title" placeholder="Search Encyclopedia">
                    
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomed' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/nosuchentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    No such an entry
{% endblock %}

{% block body %}
    <h1>No such entry</h1>
    <div>
        <p>
            Click <a href="{% url 'encyclopedia:create' %}">create</a> to generate a new page!
        </p>
    </div>

{% endblock %}